<a href="https://colab.research.google.com/github/ZUMANASHIYA/data-cleaning-projects/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [ ]:
#import numpy module with alias np
import numpy as np
from numpy.linalg import inv
import sys

In [ ]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
a = np.array([1,2,3])

In [ ]:
# print a
a

array([1, 2, 3])

In [ ]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [ ]:
#print dimentions of a,b, c and d
print("dimension of a is",a.ndim)
print("dimension of b is",b.ndim)
print("dimension of c is",c.ndim)
print("dimension of d is",d.ndim)

dimension of a is 0
dimension of b is 1
dimension of c is 2
dimension of d is 3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [ ]:
# print shape of each a,b ,c and d
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(3,)
(2, 3)
(2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
print(b.dtype)
print(d.dtype)

int64
int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function 

In [ ]:
#print type of a and b variable
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# Lets check length of array b, using len() function
print(len(b))

3


Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [ ]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array([10,20,30])
l4 = np.array([40,50,60])

Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [ ]:
%timeit [l1[i]*l2[i] for i in range(len(l1))]

The slowest run took 6.78 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 881 ns per loop


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [ ]:
#%timeit #code here
%timeit l3*l4

The slowest run took 60.41 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 582 ns per loop


so in numpy arrays I can do everything without even writing a loop? yes... ohh wao

In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it
a=np.arange(1,12,10)
print(a)

[ 1 11]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameters
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# create numpy array using eye function with 3 as passed parameter
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create a numpy array using zero function with (3,2) as passed parameter
np.zeros((3,2),dtype="int")


array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
#create a numpy array using ones function with (3,2) as passed parameter
np.ones((3,2),dtype='int')


array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
#create a numpy array using full function with (3,2) and 2 as passed parameter
np.full((3,2),2)


array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
#create a numpy array using diag function passing a list [1,2,3,4,5]
np.diag(np.arange(1,6))


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
# Create a numpy array v with [1,2,3] as its elements
v = np.array([1,2,3])

#Use tile function of numpy and pass v and (3,1) as its parametrs
np.tile(v,(3,1))


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
# Create an array with 100 values between 1 and 50 using linspace
np.linspace(1,50 , num=100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [ ]:
# Generate one random number between 0 and 1 using numpy's random.rand() function.
np.random.rand(1)


array([0.00212602])

Run the above cell again and check if number changes.

Yeah it changes. That's so random :)

In [ ]:
# so let say I want a random value between 2 and 50
np.random.randint(2,50)

48

Run the above cell again and check if number changes and its between 2 to 50.

Now lets create an array with random numbers 0 to 1 of shape 3X3

In [ ]:
#get an array as stated above
np.random.rand(3,3)

array([[0.04262803, 0.90700482, 0.01828316],
       [0.24149862, 0.01944517, 0.75822751],
       [0.65104481, 0.19806653, 0.18568657]])

In [ ]:
np.random.random([3,3])

array([[0.65849467, 0.98584157, 0.74343085],
       [0.72595257, 0.10841742, 0.9497489 ],
       [0.31059726, 0.55380865, 0.52520496]])

In [ ]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x=np.arange(1,17)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


So here x is our 1-D array along with being sweet sixteen array ;). Lets reshape our x into 2-D and 3-D array using Reshape

1. Reshaping 1-D to 2-D

In [ ]:
# Reshape x with 2 rows and 8 columns
x_new=x.reshape(2,-1)
print(x_new)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [ ]:
# reshape x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
x_new1=x.reshape(4,2,2)
print(x_new1)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


**Fun Fact:**

<u>Unknown Dimension</u>

You are allowed to have one "unknown" dimension.Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you. Awesome right?


In [ ]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
x_new2=x.reshape(4,-1)
print(x_new2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y=x.reshape(4,2,-1)

# print y
print(y)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


Note: We can not pass -1 to more than one dimension.

Another cool Fact: -1 can be used to flatten an array which means converting a multidimensional array into a 1D array.

    Lets apply this technique on y which is 3-D array

In [ ]:
# Flattening y
y.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)

# print a
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
# Get third element in array a
a[2]

6

In [ ]:
#Print 3rd, 5th, and 7th element in array a
a[3:8:2]

array([ 8, 12, 16])

Lets check the same for 2 D array

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# print the 3rd element from the 3rd row of a
a[2,2]

9

Well done!

Now lets check indexing for 3 D array 

In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(b)
print(b.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
b[0,1,2]

6

Well done.!

Have you heared about **negative indexing?**


We can use negative indexing to access an array from the end.

In [ ]:
# Print the second last element from the 2nd dim using negative indexing
b[-2,-1,-2]

5

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Slice elements from 1st to 5th element from array arr:
arr[0:5:1]


array([1, 2, 3, 4, 5])

Note: The result includes the start index, but excludes the end index.



In [ ]:
# Slice elements from index 5 to the end of the array arr:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [ ]:
# Slice elements from the beginning to index 5 (not included) in array arr:
arr[:5]


array([1, 2, 3, 4, 5])

Have you heared about **Negative Slicing?**

We can use the minus operator to refer to an index from the end:



In [ ]:
# Slice from the index 3 from the end to index 1 from the end:
arr[7:9]


array([8, 9])

**STEP**

Use the step value to determine the step of the slicing:

In [ ]:
# Print every other element from index 1 to index 7:
arr[1:7:2]


array([2, 4, 6])

Did you see? using step you were able to get alternate elements within specified index numbers.

In [ ]:
# Return every other element from the entire array arr:
arr[::2]

array([1, 3, 5, 7, 9])

well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**2. Array slicing in 2-D array.**

In [ ]:
# Print array a
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [ ]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
a[2,1:3]


array([8, 9])

In [ ]:
# In array 'a' print index 2 from all the rows :
a[:,2]


array([3, 6, 9])

In [ ]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
a[0:3,1:3]


array([[2, 3],
       [5, 6],
       [8, 9]])

Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

In [ ]:
x1= np.arange(10)

In [ ]:
# assign x2 = x1
x2=x1

In [ ]:
#print x1 and x2
print(x1)
print(x2)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Ok now you have seen that both of them are same 

In [ ]:
# change 1st element of x2 as 10
x2[0]=10

In [ ]:
#Again print x1 and x2
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [ ]:
# Check memory share between x1 and x2


True

Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [ ]:
# Create a view of x1 and store it in x3.
x3 = x1.view()
#x3[]
print(x3)

[10  1  2  3  4  5  6  7  8  9]


In [ ]:
# Again check memory share between x1 and x3


True

Woh! simple assignment is similar to view. That means 
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [ ]:
#Change 1st element of x3=100
x3[0]=100

In [ ]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


Now its proved.

Lets see how **Copy()** function works

In [ ]:
# Now create an array x4 which is copy of x1

x4=x1.copy()


In [ ]:
# Change the last element of x4 as 900
x4[-1]=900

In [ ]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [ ]:
#Check memory share between x1 and x4


False

You see! x1 and x4 don't share its memory. 

So with all our outputs we can takeaway few points:

    1. The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

    2. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

    3. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## More operations on Numpy

**1. Applying conditions**

Reference: https://thispointer.com/python-numpy-select-elements-or-indices-by-conditions-from-numpy-array/

<p style='text-align: right;'> 5 points </p>


In [ ]:
#print a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We are going to use 'a' array for all our array condition operations.


In [ ]:
# Check if every element in array a greater than 3 or not Using '>' notation
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Get a list with all elements of array 'a' grater than 3
new=a[a>3]
print(new)

[4 5 6 7 8 9]


In [ ]:
# Get a list with all elements of array 'a' greater than 3 but less than 6
new1=a[(a>3) & (a<6)]
print(new1)

[4 5]


In [ ]:
# check if each elements in array 'x1' equals array 'x4' using '==' notation
x1==x4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

You can see in above output that the last element is not same in both x1 and x4

Well done so far.

Lets check how to transpose an array

**2. Transposing array**

Reference: https://www.youtube.com/watch?v=8qpMys9ptBs

In [ ]:
# Print Transpose of array 'a'
a=np.array([[1,4,7],[2,5,8],[3,6,9]])
print(a)
#print array 'a'
print("-----------------")
transpose=(np.transpose(a))
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
-----------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In above output all the rows became columns by transposing 

In [ ]:
# stack x1 and x4 along columns.
np.vstack([x1,x4])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
#stack x1 and x4 along rows
np.hstack([x1,x4])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

Reference:https://youtu.be/D8vMQ3ADVf0
 

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

##join arr1 and arr2 along rows using concatenate() function
arr3 =np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
##join arr1 and arr2 along columns using concatenate() function
arr4 =np.concatenate((arr1,arr2),axis=0)
print(arr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [ ]:
# append arr2 to arr1
np.append(arr1,arr2)

array([1, 2, 3, 4, 5, 6, 7, 8])

Lets use insert() function which Inserts values into array before specified index value

In [ ]:
# Inserts values into array x1 before index 4 with elements of x4
np.insert(x1,4,x4)

array([0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6, 7, 8, 9])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [ ]:
# delete 2nd element from array x2
np.delete(x2,2)


array([10,  1,  3,  4,  5,  6,  7,  8,  9])

Did you see? 2 value is deleted from x2 which was at index position 2

In [ ]:
#defining a
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# print trigonometric sin value of each element of a
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [ ]:
# print trigonometric cos value of each element of a
np.cos(a)


array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [ ]:
# Print exponential value of each elements of a
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

Referal: https://numpy.org/doc/stable/reference/generated/numpy.sum.html

In [ ]:
# print total sum of elements of a
np.sum([a])

45

In [ ]:
# Print sum in array a column wise
np.sum(a,axis=1)

array([ 6, 15, 24])

In [ ]:
# Print sum in array a row wise
np.sum(a,axis=0)

array([12, 15, 18])

Refrence doc: https://numpy.org/doc/stable/reference/generated/numpy.median.html

In [ ]:
# print median of array a
np.median(a)


5.0

Refrence doc: https://numpy.org/doc/stable/reference/generated/numpy.std.html

In [ ]:
# print standard deviation of array a
np.std(a)


2.581988897471611

Refrence doc: https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html

In [ ]:
# print the determinant of array a
np.linalg.det(a)



0.0

reference doc: https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html

In [ ]:
# print the (multiplicative) inverse of array a
inv(a)

LinAlgError: ignored

Reference doc: https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html

In [ ]:
# Print the eigenvalues and right eigenvectors of array a.

w,v = np.linalg.eig(a)
print(w)
print(v)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


Reference doc: https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [ ]:
# compute dot product of arr1 and arr2
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

reference doc: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html

In [ ]:
#print largest element present in array a
np.amax(a)

9

Reference doc: https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
#print index of largest element present in array a 
np.amax(a[-1])

9

Reference doc: https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# print sorted x4 array
np.sort(x4)

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 900])

Reference doc: https://numpy.org/doc/stable/reference/generated/numpy.argsort.html

In [ ]:
# print indices of each sorted element in x4 array



array([1, 2, 3, 4, 5, 6, 7, 8, 0, 9], dtype=int64)

## Searching Arrays

Reference: https://youtu.be/zd-9D_ZCIqs

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

<p style='text-align: right;'> 4 points </p>


In [ ]:
# print the indexes where the value is 4 in array x1
new=np.where(x1==4)


Which means that the value 4 is present at index 4

You can check it by printing array x1

In [ ]:
#print array x1
print(new)

(array([4]),)


In [ ]:
# Print the indexes where the values are even in array x1
new1=np.where(x1%2==0)
print(new1)

(array([0, 2, 4, 6, 8]),)


In [ ]:
# Print x1 where x1 is greater than 5, also if number is less than 5 then replace it with 0
x6=np.where(x1>5,x1,0)
print(x6)

[100   0   0   0   0   0   6   7   8   9]
